[package]
name = "otherone-tools"
version = "0.4.0"
edition = "2021"
license = "MIT"
readme = "../../README.md"
documentation = "https://docs.rs/otherone-tools"
repository = "https://github.com/wuyoujae/otherone-agent"
keywords = ["ai", "agent", "tools"]
categories = ["asynchronous"]
description = "工具调用 — AI 请求的工具调用解析和执行"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
otherone-ai = { version = "0.4.0", path = "../otherone-ai" }

[dev-dependencies]
tokio = { workspace = true }
